import {AiFillStar} from 'react-icons/ai';

const data = [
    {
    img:'https://m.media-amazon.com/images/I/71jdOcU1RdL._AC_UL480_FMwebp_QL65_.jpg',
    title:'Top for girls',
    star: <AiFillStar className='ratings-star' />,
    reviews: "(123 reviews)",
    prevPrice: '$140.00',
    newPrice: '200',
    company: 'Tops',
    color: 'white',
    category: 'Tops',
    },

    {
    img:'https://m.media-amazon.com/images/I/717YaCfCh9L._AC_UL480_FMwebp_QL65_.jpg',
    title:'Top for girls',
    star: <AiFillStar className='ratings-star' />,
    reviews: "(123 reviews)",
    prevPrice: '$50.00',
    newPrice: '55',
    company: 'Tops',
    color: 'white',
    category: 'Tops',
    },

    {
    img:'https://m.media-amazon.com/images/I/71W50uEzSIL._AC_UL480_FMwebp_QL65_.jpg',
    title:'Top for girls',
    star: <AiFillStar className='ratings-star' />,
    reviews: "(70 reviews)",
    prevPrice: '$40.00',
     newPrice: '50',
    company: 'Tops',
    color: 'green',
    category: 'Tops',
    },
       
    {
    img:'https://m.media-amazon.com/images/I/71mZEfsvqrL._AC_UL480_FMwebp_QL65_.jpg',
    title:'Top for girls',
    star: <AiFillStar className='ratings-star' />,
    reviews: "(12 reviews)",
    prevPrice: '$140.00',
     newPrice: '100',
    company: 'Tops',
    color: 'orange',
    category: 'Tops',
    },

    {
    img:'https://m.media-amazon.com/images/I/71abceUNWqL._AC_UL480_FMwebp_QL65_.jpg',
    title:'Kurta pair',
    star: <AiFillStar className='ratings-star' />,
    reviews: "(12 reviews)",
    prevPrice: '$90.00',
    newPrice: '150',
    company: 'Kurta',
    color: 'green',
    category: 'Kurta',
    },

    {
        img:'https://m.media-amazon.com/images/I/71NAVaW1DDL._AC_UL480_FMwebp_QL65_.jpg',
        title:'Kurta pair',
        star: <AiFillStar className='ratings-star' />,
        reviews: "(50 reviews)",
        prevPrice: '$140.00',
        newPrice: '200',
        company: 'Kurta',
        color: 'white',
        category: 'Kurta',
        },

    {
    img:'https://m.media-amazon.com/images/I/61pQaaYu86L._AC_UL480_FMwebp_QL65_.jpg',
    title:'Kurta pair',
    star: <AiFillStar className='ratings-star' />,
    reviews: "(123 reviews)",
    prevPrice: '$140.00',
    newPrice: '200',
    company: 'Kurta',
    color: 'Pink',
    category: 'Kurta',   
    },
    
    {
    img:'https://m.media-amazon.com/images/I/81GNVX+klYL._AC_UL480_FMwebp_QL65_.jpg',
    title:'Kurta pair',
    star: <AiFillStar className='ratings-star' />,
    reviews: "(123 reviews)",
    prevPrice: '$140.00',
    newPrice: '200',
    company: 'Kurta',
    color: 'Orange',
    category: 'Kurta',    
    },

    
    
    {
    img:'https://m.media-amazon.com/images/I/71WTxTRa1NL._AC_UL480_FMwebp_QL65_.jpg',
    title:'Kurta pair',
    star: <AiFillStar className='ratings-star' />,
    reviews: "(123 reviews)",
    prevPrice: '$140.00',
    newPrice: '200',
    company: 'Kurta',
    color: 'green',
    category: 'Kurta',     
    },
    
    {
    img:'https://m.media-amazon.com/images/I/71e44AY6RrL._AC_UL480_FMwebp_QL65_.jpg',
    title:'Kurta pair',
    star: <AiFillStar className='ratings-star' />,
    reviews: "(23 reviews)",
    prevPrice: '$140.00',
    newPrice: '50',
    company: 'Kurta',
    color: 'pink',
    category: 'Kurta',
    },

    {
    img:'https://m.media-amazon.com/images/I/71cFoTJ+odL._MCnd_AC_UL480_FMwebp_QL65_.jpg',
    title:'Kurta pair',
    star: <AiFillStar className='ratings-star' />,
    reviews: "(30 reviews)",
    prevPrice: '$140.00',
    newPrice: '150',
    company: 'Kurta',
    color: 'blue',
    category: 'Kurta',
    },

    {
    img:'https://m.media-amazon.com/images/I/61e6OB6ypeL._AC_UY327_FMwebp_QL65_.jpg',
    title:'Kurta pair',
    star: <AiFillStar className='ratings-star' />,
    reviews: "(123 reviews)",
    prevPrice: '$140.00',
    newPrice: '200',
    company: 'Kurta',
    color: 'black',
    category: 'Kurta',
    },

    {
    img:'https://m.media-amazon.com/images/I/81G4gBhCfrL._AC_UL480_FMwebp_QL65_.jpg',
    title:'Top for girls',
    star: <AiFillStar className='ratings-star' />,
    reviews: "(123 reviews)",
    prevPrice: '$50.00',
    newPrice: '50',
    company: 'Tops',
    color: 'white',
    category: 'Tops',
    },

    {
    img:'https://m.media-amazon.com/images/I/91X7ckDnNLS._AC_UY327_FMwebp_QL65_.jpg',
    title:'Kurta pair',
    star: <AiFillStar className='ratings-star' />,
    reviews: "(123 reviews)",
    prevPrice: '$140.00',
    newPrice: '200',
    company: 'Kurta',
    color: 'green',
    category: 'Kurta',
    },

    {
        img:'https://m.media-amazon.com/images/I/81g4poBjeyL._AC_UL480_FMwebp_QL65_.jpg',
        title:'Top for girls',
        star: <AiFillStar className='ratings-star' />,
        reviews: "(12 reviews)",
        prevPrice: '$140.00',
        newPrice: '100',
        company: 'Tops',
        color: 'blue',
        category: 'Tops',
        },



        {
            img:'https://m.media-amazon.com/images/I/71sBr4Nr1sL._AC_UL480_FMwebp_QL65_.jpg',
            title:'Kids wear',
            star: <AiFillStar className='ratings-star' />,
            reviews: "(300 reviews)",
            prevPrice: '$140.00',
            newPrice: '200',
            company: 'Kids',
            color: 'white',
            category: 'Kids',
            },

            {
                img:'https://m.media-amazon.com/images/I/616-VsyPRTL._AC_UL480_FMwebp_QL65_.jpg',
                title:'Kids wear',
                star: <AiFillStar className='ratings-star' />,
                reviews: "(123 reviews)",
                prevPrice: '$140.00',
                newPrice: '200',
                company: 'Kids',
                color: 'black',
                category: 'Kids',
                },

                {
                    img:'https://m.media-amazon.com/images/I/61NzuC03HNL._AC_UL480_QL65_T2F_.jpg',
                    title:'Kids wear',
                    star: <AiFillStar className='ratings-star' />,
                    reviews: "(123 reviews)",
                    prevPrice: '$140.00',
                    newPrice: '200',
                    company: 'Kids',
                    color: 'pink',
                    category: 'Kids',
                    },

                    {
                        img:'https://m.media-amazon.com/images/I/911bBzw+xTL._AC_UL480_QL65_T2F_.jpg',
                        title:'Kids wear',
                        star: <AiFillStar className='ratings-star' />,
                        reviews: "(123 reviews)",
                        prevPrice: '$200.00',
                        newPrice: '150',
                        company: 'Kids',
                        color: 'blue',
                        category: 'Kids',
                        },

                        {
                            img:'https://m.media-amazon.com/images/I/61NzuC03HNL._AC_UL480_QL65_T2F_.jpg',
                            title:'Kids wear',
                            star: <AiFillStar className='ratings-star' />,
                            reviews: "(123 reviews)",
                            prevPrice: '$140.00',
                            newPrice: '200',
                            company: 'Kids',
                            color: 'pink',
                            category: 'Kids',
                            },

                            {
                                img:'https://m.media-amazon.com/images/I/51Sux8nUx2L._MCnd_AC_UL480_QL65_T2F_.jpg',
                                title:'Kids wear',
                                star: <AiFillStar className='ratings-star' />,
                                reviews: "(123 reviews)",
                                prevPrice: '$140.00',
                                newPrice: '200',
                                company: 'Kids',
                                color: 'blue',
                                category: 'Kids',
                                },
                                {
                                    img:'https://m.media-amazon.com/images/I/A1agN1MSRDL._AC_UL480_FMwebp_QL65_.jpg',
                                    title:'Tshirts',
                                    star: <AiFillStar className='ratings-star' />,
                                    reviews: "(23 reviews)",
                                    prevPrice: '$140.00',
                                    newPrice: '200',
                                    company: 'Tshirts',
                                    color: 'green',
                                    category: 'Tshirts',
                                    },

                                    {
                                        img:'https://m.media-amazon.com/images/I/91oIjIbYeuL._AC_UL480_FMwebp_QL65_.jpg',
                                        title:'Tshirts',
                                        star: <AiFillStar className='ratings-star' />,
                                        reviews: "(123 reviews)",
                                        prevPrice: '$90.00',
                                        newPrice: '100',
                                        company: 'Tshirts',
                                        color: 'blue',
                                        category: 'Tshirts',
                                        },

                                        {
                                            img:'https://m.media-amazon.com/images/I/71zRMNf2uvL._AC_UL480_FMwebp_QL65_.jpg',
                                            title:'Tshirts',
                                            star: <AiFillStar className='ratings-star' />,
                                            reviews: "(123 reviews)",
                                            prevPrice: '$300.00',
                                            newPrice: '200',
                                            company: 'Tshirts',
                                            color: 'black',
                                            category: 'Tshirts',
                                            },

                                            {
                                                img:'https://m.media-amazon.com/images/I/71gUMB0Q-hL._AC_UY327_FMwebp_QL65_.jpg',
                                                title:'Top for girls',
                                                star: <AiFillStar className='ratings-star' />,
                                                reviews: "(123 reviews)",
                                                prevPrice: '$300.00',
                                                newPrice: '200',
                                                company: 'Tops',
                                                color: 'blue',
                                                category: 'Tops',
                                                },
]

export default data;